"""add kiosk, drop off, ledger and redemption tables

Revision ID: 7751a41bc3c1
Revises: 6bfe14bf448c
Create Date: 2026-10-06 12:01:43.853298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7751a41bc3c1'
down_revision: Union[str, Sequence[str], None] = '6bfe14bf448c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosk',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('opening_time', sa.String(length=255), nullable=False),
    sa.Column('closing_time', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kiosk')),
    sa.UniqueConstraint('id', name=op.f('uq_kiosk_id'))
    )
    op.create_table('drop_off_event',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('kiosk_id', sa.String(length=255), nullable=False),
    sa.Column('collector_id', sa.String(length=255), nullable=False),
    sa.Column('depositor_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['user.id'], name=op.f('fk_drop_off_event_collector_id_user')),
    sa.ForeignKeyConstraint(['depositor_id'], ['user.id'], name=op.f('fk_drop_off_event_depositor_id_user')),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosk.id'], name=op.f('fk_drop_off_event_kiosk_id_kiosk')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drop_off_event')),
    sa.UniqueConstraint('id', name=op.f('uq_drop_off_event_id'))
    )
    op.create_table('redemption',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('depositor_id', sa.String(length=255), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['depositor_id'], ['user.id'], name=op.f('fk_redemption_depositor_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redemption')),
    sa.UniqueConstraint('id', name=op.f('uq_redemption_id'))
    )
    op.create_table('drop_off_event_item',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('waste_type', sa.String(length=255), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('drop_off_event_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['drop_off_event_id'], ['drop_off_event.id'], name=op.f('fk_drop_off_event_item_drop_off_event_id_drop_off_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drop_off_event_item')),
    sa.UniqueConstraint('id', name=op.f('uq_drop_off_event_item_id'))
    )
    op.create_table('point_transaction',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('depositor_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('drop_off_event_id', sa.String(length=255), nullable=True),
    sa.Column('redemption_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['depositor_id'], ['user.id'], name=op.f('fk_point_transaction_depositor_id_user')),
    sa.ForeignKeyConstraint(['drop_off_event_id'], ['drop_off_event.id'], name=op.f('fk_point_transaction_drop_off_event_id_drop_off_event')),
    sa.ForeignKeyConstraint(['redemption_id'], ['redemption.id'], name=op.f('fk_point_transaction_redemption_id_redemption')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point_transaction')),
    sa.UniqueConstraint('drop_off_event_id', name=op.f('uq_point_transaction_drop_off_event_id')),
    sa.UniqueConstraint('id', name=op.f('uq_point_transaction_id')),
    sa.UniqueConstraint('redemption_id', name=op.f('uq_point_transaction_redemption_id'))
    )
    op.add_column('user', sa.Column('kiosk_id', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_phone_key'), 'user', type_='unique')
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    op.create_unique_constraint(op.f('uq_user_phone'), 'user', ['phone'])
    op.create_foreign_key(op.f('fk_user_kiosk_id_kiosk'), 'user', 'kiosk', ['kiosk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_kiosk_id_kiosk'), 'user', type_='foreignkey')
    op.drop_constraint(op.f('uq_user_phone'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.create_unique_constraint(op.f('user_phone_key'), 'user', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'kiosk_id')
    op.drop_table('point_transaction')
    op.drop_table('drop_off_event_item')
    op.drop_table('redemption')
    op.drop_table('drop_off_event')
    op.drop_table('kiosk')
    # ### end Alembic commands ###
